apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::823033372288:role/eksctl-spot-cluster-nodegroup-spot-NodeInstanceRole-qy40fvCu72w0
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::823033372288:user/roboshop-admin
      username: roboshop-admin
kind: ConfigMap
metadata:
  creationTimestamp: "2024-02-26T11:13:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "74472"
  uid: 6c9892d9-b7ad-4725-8ee7-c71aea137233



 