apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::823033372288:role/eksctl-spot-cluster-nodegroup-spot-NodeInstanceRole-qy40fvCu72w0
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: aarn:aws:iam::823033372288:user/roboshop-admin
      username: roboshop-admin
kind: ConfigMap
metadata:
  creationTimestamp: "2024-02-26T05:13:01Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1224"
  uid: 73821be4-d8b4-4d12-8d8d-3b9510c476ad


 