---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    name: mongodb
  clusterIP: None #headless service
  selector:
    name: mongodb
    tier: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      name: mongodb
      tier: db # has to match .spec.template.metadata.labels
  serviceName: "mongodb"
  replicas: 2 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: mongodb # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: mshiva7396/mongodb:v1
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongodb-volume
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: mongodb-volume
    spec:
      accessModes: [ "ReadWriteOnce" ] 
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi
